---
- name: Сетевая диагностика кластера
  hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Получить MAC и IP для enp0s8
      set_fact:
        mac: "{{ ansible_facts['enp0s8']['macaddress'] }}"
        ip: "{{ ansible_facts['enp0s8']['ipv4']['address'] }}"

    - name: Вывод в формате для резервирования
      debug:
        msg: "{{ inventory_hostname }} | MAC: {{ mac }} | IP: {{ ip }}"